// Find the Word — hand-curated look-alike distractor manifest, one entry
// per curriculum word (all 200). Same manifest+coverage-check contract as
// `src/letters/letterStrokes.js` / `wordArtManifest.json`: a static,
// reviewed data file plus a build-time coverage check
// (scripts/check-findtheword-sync.mjs), not a runtime algorithm.
//
// Why hand-curated instead of algorithmic (see docs/ACTIVITY_ROSTER_REPORT.md
// FIND THE WORD section for the full assessment): a same-first-letter/
// length/edit-distance heuristic over the 200-word curriculum reaches ~94%
// coverage at >=3 candidates, but the matches it produces are frequently
// semantically/visually noisy (e.g. "juice"~"jump", "grapes"~"green") --
// unacceptable given the distractor quality IS this activity's entire
// pedagogical point (Blank's whole-word look-alike discrimination). Every
// entry below is a real, simple, age-appropriate English word, preferring
// another curriculum word where a genuine look-alike exists (free
// double-exposure to the 200-word list) and padding with a common
// non-curriculum real word otherwise. None are the target's own
// plural/tense/derivational inflection (ruled out entirely rather than
// resolved case-by-case against the audibility-uniqueness rule).
export const FIND_THE_WORD_LOOKALIKES = {
  cat: ['bat', 'hat', 'cap'],
  dog: ['dig', 'dot', 'fog'],
  bird: ['girl', 'dirt', 'shirt'],
  fish: ['dish', 'wish', 'fist'],
  bear: ['bean', 'beat', 'wear'],
  ball: ['tall', 'call', 'wall'],
  book: ['look', 'cook', 'hook'],
  cup: ['cut', 'cub', 'cap'],
  frog: ['fog', 'from', 'drop'],
  horse: ['house', 'hose', 'worse'],
  lion: ['line', 'loan', 'lawn'],
  rabbit: ['habit', 'ribbon', 'robot'],
  duck: ['dock', 'luck', 'tuck'],
  cow: ['how', 'now', 'cot'],
  pig: ['big', 'dig', 'wig'],
  turtle: ['turkey', 'tumble', 'bottle'],
  eat: ['ear', 'eight', 'east'],
  jump: ['dump', 'hump', 'lump'],
  run: ['sun', 'fun', 'bun'],
  swim: ['swing', 'slim', 'trim'],
  fly: ['fry', 'sky', 'cry'],
  dance: ['chance', 'dense', 'dine'],
  sing: ['ring', 'king', 'wing'],
  play: ['pray', 'clay', 'stay'],
  stop: ['step', 'shop', 'spot'],
  go: ['no', 'so', 'to'],
  look: ['book', 'cook', 'hook'],
  see: ['bee', 'tree', 'free'],
  help: ['held', 'kelp', 'yelp'],
  sleep: ['sheep', 'steep', 'sleet'],
  open: ['oven', 'omen', 'often'],
  sit: ['fit', 'sip', 'hit'],
  big: ['pig', 'wig', 'dig'],
  small: ['smell', 'stall', 'shall'],
  hot: ['hat', 'hut', 'hop'],
  cold: ['gold', 'bold', 'sold'],
  happy: ['puppy', 'poppy', 'sappy'],
  sad: ['bad', 'mad', 'sat'],
  fast: ['last', 'past', 'mast'],
  slow: ['snow', 'glow', 'blow'],
  mom: ['mop', 'mob', 'mow'],
  dad: ['dab', 'dam', 'bad'],
  baby: ['belly', 'body', 'bunny'],
  boy: ['toy', 'joy', 'buy'],
  girl: ['curl', 'twirl', 'whirl'],
  friend: ['fried', 'front', 'trend'],
  man: ['can', 'fan', 'pan'],
  woman: ['human', 'wooden', 'woken'],
  apple: ['apply', 'ripple', 'angle'],
  milk: ['silk', 'bulk', 'mild'],
  cookie: ['rookie', 'cooker', 'cooking'],
  cake: ['lake', 'bake', 'rake'],
  pizza: ['dizzy', 'plaza', 'puzzle'],
  bread: ['break', 'dread', 'tread'],
  egg: ['leg', 'peg', 'keg'],
  water: ['waiter', 'wafer', 'later'],
  red: ['bed', 'fed', 'led'],
  blue: ['glue', 'clue', 'blur'],
  green: ['greed', 'greet', 'screen'],
  yellow: ['mellow', 'bellow', 'fellow'],
  orange: ['arrange', 'strange', 'change'],
  purple: ['purpose', 'people', 'simple'],
  pink: ['link', 'sink', 'wink'],
  black: ['block', 'clack', 'crack'],
  bed: ['red', 'fed', 'led'],
  chair: ['choir', 'chain', 'chart'],
  door: ['poor', 'floor', 'deer'],
  house: ['horse', 'mouse', 'hose'],
  car: ['care', 'cart', 'card'],
  bus: ['bun', 'but', 'bug'],
  hat: ['hut', 'hot', 'bat'],
  shoe: ['show', 'shore', 'shone'],
  one: ['once', 'bone', 'cone'],
  two: ['tow', 'toe', 'top'],
  three: ['there', 'threw', 'throne'],
  four: ['your', 'sour', 'hour'],
  five: ['dive', 'hive', 'live'],
  six: ['fix', 'mix', 'sick'],
  seven: ['even', 'sever', 'eleven'],
  ten: ['hen', 'pen', 'den'],
  nine: ['mine', 'dine', 'wine'],
  eight: ['sight', 'night', 'height'],
  zero: ['hero', 'zebra', 'zeal'],
  the: ['she', 'then', 'they'],
  a: ['an', 'at', 'I'],
  is: ['it', 'in', 'as'],
  not: ['now', 'no', 'net'],
  can: ['man', 'cap', 'cat'],
  and: ['ant', 'any', 'sand'],
  or: ['our', 'on', 'of'],
  but: ['bus', 'bud', 'cut'],
  this: ['thus', 'that', 'thin'],
  I: ['if', 'in', 'it'],
  you: ['your', 'young', 'youth'],
  he: ['her', 'help', 'hen'],
  she: ['the', 'shed', 'shoe'],
  we: ['wet', 'web', 'went'],
  they: ['the', 'them', 'there'],
  me: ['men', 'met', 'mean'],
  my: ['may', 'by', 'me'],
  in: ['is', 'it', 'on'],
  on: ['in', 'one', 'or'],
  up: ['us', 'cup', 'pup'],
  down: ['gown', 'town', 'clown'],
  to: ['go', 'so', 'toy'],
  at: ['as', 'art', 'am'],
  for: ['far', 'fort', 'form'],
  with: ['wish', 'witch', 'width'],
  good: ['food', 'hood', 'wood'],
  bad: ['bat', 'bag', 'bed'],
  pretty: ['petty', 'party', 'plenty'],
  funny: ['bunny', 'sunny', 'runny'],
  new: ['few', 'now', 'sew'],
  old: ['gold', 'cold', 'bold'],
  loud: ['cloud', 'aloud', 'proud'],
  quiet: ['quite', 'quit', 'quiz'],
  read: ['bread', 'lead', 'real'],
  write: ['white', 'wrist', 'wire'],
  draw: ['claw', 'straw', 'drama'],
  learn: ['earn', 'yearn', 'lean'],
  count: ['mount', 'county', 'fount'],
  share: ['shark', 'spare', 'stare'],
  color: ['colon', 'collar', 'cellar'],
  cut: ['cup', 'cat', 'but'],
  sun: ['run', 'fun', 'bun'],
  moon: ['moan', 'noon', 'spoon'],
  star: ['stir', 'scar', 'start'],
  rain: ['main', 'pain', 'train'],
  snow: ['slow', 'show', 'grow'],
  wind: ['wine', 'wing', 'find'],
  tree: ['free', 'three', 'treat'],
  flower: ['flour', 'slower', 'grower'],
  hand: ['band', 'land', 'sand'],
  foot: ['food', 'fool', 'boot'],
  eye: ['dye', 'rye', 'bye'],
  ear: ['eat', 'early', 'year'],
  nose: ['rose', 'hose', 'note'],
  mouth: ['month', 'south', 'youth'],
  head: ['bread', 'bead', 'read'],
  heart: ['heard', 'earth', 'hear'],
  do: ['go', 'so', 'to'],
  it: ['in', 'is', 'at'],
  that: ['this', 'than', 'chat'],
  all: ['ball', 'tall', 'call'],
  more: ['core', 'sore', 'store'],
  no: ['go', 'so', 'not'],
  yes: ['yet', 'yell', 'eyes'],
  now: ['not', 'how', 'cow'],
  monkey: ['money', 'mommy', 'hockey'],
  shark: ['share', 'sharp', 'stark'],
  ant: ['and', 'art', 'aunt'],
  bee: ['see', 'tree', 'free'],
  soup: ['soap', 'scoop', 'group'],
  juice: ['voice', 'spice', 'mice'],
  banana: ['bandana', 'cabana', 'banner'],
  grapes: ['grades', 'drapes', 'scrapes'],
  white: ['write', 'while', 'whine'],
  brown: ['crown', 'frown', 'brow'],
  gray: ['pray', 'tray', 'grab'],
  gold: ['cold', 'old', 'bold'],
  many: ['any', 'man', 'money'],
  push: ['bush', 'gush', 'posh'],
  pull: ['bull', 'full', 'gull'],
  throw: ['throat', 'grow', 'growl'],
  catch: ['match', 'patch', 'watch'],
  stand: ['sand', 'strand', 'grand'],
  hop: ['top', 'mop', 'hip'],
  clean: ['glean', 'clear', 'clan'],
  dirty: ['thirty', 'dirt', 'thirsty'],
  wet: ['yet', 'vet', 'web'],
  dry: ['cry', 'fry', 'try'],
  full: ['pull', 'bull', 'fall'],
  empty: ['simply', 'envy', 'empire'],
  phone: ['prone', 'phony', 'shone'],
  light: ['night', 'sight', 'tight'],
  clock: ['block', 'flock', 'click'],
  table: ['cable', 'stable', 'fable'],
  pencil: ['stencil', 'pretzel', 'pen'],
  paper: ['pepper', 'caper', 'vapor'],
  box: ['fox', 'ox', 'boy'],
  bag: ['bat', 'big', 'bad'],
  sky: ['shy', 'sly', 'spy'],
  cloud: ['loud', 'proud', 'aloud'],
  fire: ['hire', 'wire', 'tire'],
  ice: ['ace', 'rice', 'nice'],
  hair: ['fair', 'hail', 'chair'],
  arm: ['army', 'art', 'aim'],
  leg: ['egg', 'let', 'log'],
  teeth: ['teach', 'tenth', 'wreath'],
  here: ['there', 'hare', 'herd'],
  there: ['where', 'here', 'three'],
  then: ['them', 'the', 'when'],
  after: ['later', 'faster', 'master'],
  before: ['bore', 'store', 'beware'],
  so: ['no', 'go', 'to'],
  because: ['became', 'before', 'cause'],
  when: ['then', 'hen', 'went'],
  where: ['there', 'were', 'wheel'],
  what: ['that', 'hat', 'want'],
  how: ['cow', 'now', 'who'],
};

// Coverage guarantee consumed by scripts/check-findtheword-sync.mjs — every
// curriculum word must resolve to exactly 3 distinct real-word distractors,
// none equal to the target itself.
export function getLookalikes(word) {
  return FIND_THE_WORD_LOOKALIKES[word] ?? null;
}
